# frame frame_display settings
FRAME_DISPLAY_COLOR = "#5d8aa8"
FRAME_DISPLAY_HEIGHT = 100
FRAME_DISPLAY_WIDTH = 800
FRAME_DISPLAY_BORDERWIDTH = 5

# frame frame_button settings
FRAME_BUTTON_COLOR = "#282c34"
FRAME_BUTTON_HEIGHT = 400
FRAME_BUTTON_WIDTH = 800
FRAME_BUTTON_BORDERWIDTH = 5

# frame frame_menu settings
FRAME_MENU_HEIGHT = 20
FRAME_MENU_WIDTH = 800
